// <auto-generated />
namespace RestaurantManager.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class M3 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(M3));
        
        string IMigrationMetadata.Id
        {
            get { return "202208282151586_M3"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
