// <auto-generated />
namespace RestaurantManager.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class M30 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(M30));
        
        string IMigrationMetadata.Id
        {
            get { return "202310260959340_M30"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
